// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Productc.Infrastructure.Persistense;

#nullable disable

namespace Productc.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421062818_intialize001")]
    partial class intialize001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Productc.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14b23867-0427-479f-be37-d2c43ea58ad5"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Powerful laptop with 16GB RAM",
                            ImageUrl = "/images/laptop.jpg",
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 1200.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5d247699-e967-4402-aae7-7684067fc639"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest model smartphone",
                            ImageUrl = "/images/smartphone.jpg",
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 899.50m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f08947ac-d588-4182-8d5c-bbb41306b952"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise-cancelling headphones",
                            ImageUrl = "/images/headphones.jpg",
                            IsDeleted = false,
                            Name = "Headphones",
                            Price = 199.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d8cbdfd5-2bfc-40e1-bdf5-16cc3afe9338"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic RGB gaming mouse",
                            ImageUrl = "/images/mouse.jpg",
                            IsDeleted = false,
                            Name = "Gaming Mouse",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("54791ee7-2b13-4ba6-bfd1-51ee525e66f1"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mechanical keyboard with RGB",
                            ImageUrl = "/images/keyboard.jpg",
                            IsDeleted = false,
                            Name = "Keyboard",
                            Price = 89.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9551696b-4e79-4d2e-8744-1934b7878777"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "27-inch 4K UHD monitor",
                            ImageUrl = "/images/monitor.jpg",
                            IsDeleted = false,
                            Name = "Monitor",
                            Price = 349.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("32f648e7-302a-4f28-a61a-6b815cc91d9f"),
                            Category = "Wearables",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fitness and health tracking",
                            ImageUrl = "/images/smartwatch.jpg",
                            IsDeleted = false,
                            Name = "Smartwatch",
                            Price = 159.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b7d6da3-ca01-44ca-b072-5f4be3b969e6"),
                            Category = "Audio",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable waterproof speaker",
                            ImageUrl = "/images/speaker.jpg",
                            IsDeleted = false,
                            Name = "Bluetooth Speaker",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c86a40f1-47e7-4083-9cb5-bcf62927e641"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1080p HD webcam for streaming",
                            ImageUrl = "/images/webcam.jpg",
                            IsDeleted = false,
                            Name = "Webcam",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("39e258a5-4f19-4cf7-aec6-79b8e5598a34"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10-inch Android tablet",
                            ImageUrl = "/images/tablet.jpg",
                            IsDeleted = false,
                            Name = "Tablet",
                            Price = 299.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8e555136-60d5-4c83-a561-54a34a39f50c"),
                            Category = "Storage",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1TB USB 3.0 drive",
                            ImageUrl = "/images/hdd.jpg",
                            IsDeleted = false,
                            Name = "External Hard Drive",
                            Price = 69.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("625c08e9-6566-4022-96bd-1af13da67833"),
                            Category = "Storage",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "500GB NVMe SSD",
                            ImageUrl = "/images/ssd.jpg",
                            IsDeleted = false,
                            Name = "SSD",
                            Price = 89.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("47bcc66f-1d6c-4f8b-8f5c-25ab13285071"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast USB-C charger",
                            ImageUrl = "/images/charger.jpg",
                            IsDeleted = false,
                            Name = "Charger",
                            Price = 29.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b742d2f0-55ba-40ad-b080-f3181d50150b"),
                            Category = "Networking",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi 6 dual-band router",
                            ImageUrl = "/images/router.jpg",
                            IsDeleted = false,
                            Name = "Router",
                            Price = 129.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1b49186f-9fce-4c53-acc3-f737f80dc5e1"),
                            Category = "Office",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All-in-one inkjet printer",
                            ImageUrl = "/images/printer.jpg",
                            IsDeleted = false,
                            Name = "Printer",
                            Price = 149.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a795d5cc-fac4-47ac-a2a1-a1bc3d809549"),
                            Category = "Home Office",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LED lamp with adjustable brightness",
                            ImageUrl = "/images/lamp.jpg",
                            IsDeleted = false,
                            Name = "Desk Lamp",
                            Price = 39.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("52b919a6-c75d-4cc4-b4f3-4de0aa5f2079"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic mesh office chair",
                            ImageUrl = "/images/chair.jpg",
                            IsDeleted = false,
                            Name = "Office Chair",
                            Price = 199.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ba393abb-d394-4598-9e80-320a57b830df"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof tech backpack",
                            ImageUrl = "/images/backpack.jpg",
                            IsDeleted = false,
                            Name = "Backpack",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c3fc2c37-e2a6-474a-bf4f-cfbea7a42e42"),
                            Category = "Gadgets",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mini drone with camera",
                            ImageUrl = "/images/drone.jpg",
                            IsDeleted = false,
                            Name = "Drone",
                            Price = 129.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("708fc674-82da-4a30-9ae9-9f55e0bed9ae"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable tripod for cameras",
                            ImageUrl = "/images/tripod.jpg",
                            IsDeleted = false,
                            Name = "Tripod",
                            Price = 34.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("90db36e2-4dbb-496c-b49b-22476c81bacf"),
                            Category = "Photography",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DSLR camera with lens kit",
                            ImageUrl = "/images/camera.jpg",
                            IsDeleted = false,
                            Name = "Camera",
                            Price = 599.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dc4e9278-2e29-4447-b322-c3c34de5040a"),
                            Category = "Appliances",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Programmable coffee maker",
                            ImageUrl = "/images/coffeemaker.jpg",
                            IsDeleted = false,
                            Name = "Coffee Maker",
                            Price = 89.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7ddca6aa-5abb-47b9-b28e-e2794844db98"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1.7L cordless kettle",
                            ImageUrl = "/images/kettle.jpg",
                            IsDeleted = false,
                            Name = "Electric Kettle",
                            Price = 39.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af9fce44-a892-4fdc-8446-bcd98ae2cf72"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact 700W microwave",
                            ImageUrl = "/images/microwave.jpg",
                            IsDeleted = false,
                            Name = "Microwave Oven",
                            Price = 119.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("28d93672-89dd-4042-8e05-b6d0bd7ef87c"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed blender",
                            ImageUrl = "/images/blender.jpg",
                            IsDeleted = false,
                            Name = "Blender",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c723bb4-3c0d-4114-b0fa-f5439cae3490"),
                            Category = "Wearables",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tracks steps and heart rate",
                            ImageUrl = "/images/tracker.jpg",
                            IsDeleted = false,
                            Name = "Fitness Tracker",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2c8da045-9a52-49e5-8184-5c31850c5a4e"),
                            Category = "Entertainment",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable mini projector",
                            ImageUrl = "/images/projector.jpg",
                            IsDeleted = false,
                            Name = "Projector",
                            Price = 229.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6594ffaf-cd8c-4507-a80a-8083c9d0b3d0"),
                            Category = "Entertainment",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart 55-inch 4K TV",
                            ImageUrl = "/images/tv.jpg",
                            IsDeleted = false,
                            Name = "TV",
                            Price = 599.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f7919d34-98fb-4ac6-9f1b-83b4058f3a0b"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10000mAh portable charger",
                            ImageUrl = "/images/powerbank.jpg",
                            IsDeleted = false,
                            Name = "Power Bank",
                            Price = 29.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7ada0ae4-1c87-47b6-bec4-6fba1fe4982d"),
                            Category = "Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oscillating pedestal fan",
                            ImageUrl = "/images/fan.jpg",
                            IsDeleted = false,
                            Name = "Fan",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f94b53ee-e1b4-4ec0-9236-17fd60f48df8"),
                            Category = "Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric space heater",
                            ImageUrl = "/images/heater.jpg",
                            IsDeleted = false,
                            Name = "Heater",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9bcab733-d2ae-4748-9596-2f01358318d4"),
                            Category = "Tools",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Household tool set",
                            ImageUrl = "/images/toolkit.jpg",
                            IsDeleted = false,
                            Name = "Tool Kit",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d6b49cf-1bbf-4bac-96ef-7d468d76db4a"),
                            Category = "Tools",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Magnetic precision screwdriver set",
                            ImageUrl = "/images/screwdrivers.jpg",
                            IsDeleted = false,
                            Name = "Screwdriver Set",
                            Price = 24.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1247b855-0ade-4b0c-beb4-fe86c2486a80"),
                            Category = "Tools",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable LED flashlight",
                            ImageUrl = "/images/flashlight.jpg",
                            IsDeleted = false,
                            Name = "Flashlight",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef0fed9f-c7eb-4bb9-be16-3ffee170ee6d"),
                            Category = "Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HEPA filter air purifier",
                            ImageUrl = "/images/purifier.jpg",
                            IsDeleted = false,
                            Name = "Air Purifier",
                            Price = 149.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5216746d-47cf-4f87-b45d-77b375fe69df"),
                            Category = "Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cordless stick vacuum",
                            ImageUrl = "/images/vacuum.jpg",
                            IsDeleted = false,
                            Name = "Vacuum Cleaner",
                            Price = 189.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8d09021f-0e52-4f31-b70e-4db07a7a5d06"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2-slice toaster with browning control",
                            ImageUrl = "/images/toaster.jpg",
                            IsDeleted = false,
                            Name = "Toaster",
                            Price = 34.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1005d4ee-73cd-4b2a-a485-8b18e7fffe21"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-function rice cooker",
                            ImageUrl = "/images/ricecooker.jpg",
                            IsDeleted = false,
                            Name = "Rice Cooker",
                            Price = 69.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7afec4a5-9c77-4168-bee5-20556a1719d7"),
                            Category = "Appliances",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Steam iron with anti-drip",
                            ImageUrl = "/images/iron.jpg",
                            IsDeleted = false,
                            Name = "Iron",
                            Price = 39.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c37f358a-9cb1-4279-8ee5-e03aa3485edc"),
                            Category = "Appliances",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional hair dryer",
                            ImageUrl = "/images/hairdryer.jpg",
                            IsDeleted = false,
                            Name = "Hair Dryer",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("83fe2da9-1fa6-4ec7-88eb-a66aa6f0963e"),
                            Category = "Smart Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Color-changing smart bulb",
                            ImageUrl = "/images/smartlight.jpg",
                            IsDeleted = false,
                            Name = "Smart Light",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1344017d-fbdc-4007-bf26-d9b29b00ee52"),
                            Category = "Smart Home",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi home security camera",
                            ImageUrl = "/images/securitycam.jpg",
                            IsDeleted = false,
                            Name = "Security Camera",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0a85214b-196b-4606-ba95-940aef53a229"),
                            Category = "Entertainment",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4K streaming media player",
                            ImageUrl = "/images/streamingstick.jpg",
                            IsDeleted = false,
                            Name = "Streaming Stick",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a6af424d-f0e7-4c39-852e-5560fccc2a25"),
                            Category = "Personal Care",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable electric shaver",
                            ImageUrl = "/images/shaver.jpg",
                            IsDeleted = false,
                            Name = "Electric Shaver",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eb05e902-890d-40ce-b8b7-b7d2b7e5fcba"),
                            Category = "Personal Care",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electric toothbrush with timer",
                            ImageUrl = "/images/toothbrush.jpg",
                            IsDeleted = false,
                            Name = "Toothbrush",
                            Price = 29.99m,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Productc.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
