// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Productc.Api.DataAccess;

#nullable disable

namespace Productc.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Productc.Api.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4575d5ad-2379-4abb-81df-8c1e9a2d1eee"),
                            Category = "Electronics",
                            Description = "Powerful laptop with 16GB RAM",
                            ImageUrl = "/images/laptop.jpg",
                            Name = "Laptop",
                            Price = 1200.99m
                        },
                        new
                        {
                            Id = new Guid("a1a17ce4-5190-44a0-bcd2-917360573112"),
                            Category = "Electronics",
                            Description = "Latest model smartphone",
                            ImageUrl = "/images/smartphone.jpg",
                            Name = "Smartphone",
                            Price = 899.50m
                        },
                        new
                        {
                            Id = new Guid("35b86b13-5ba2-4612-91d9-c63809d03079"),
                            Category = "Electronics",
                            Description = "Noise-cancelling headphones",
                            ImageUrl = "/images/headphones.jpg",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("15f6d37e-35a3-4926-a8ed-8ecdc4f4cb74"),
                            Category = "Accessories",
                            Description = "Ergonomic RGB gaming mouse",
                            ImageUrl = "/images/mouse.jpg",
                            Name = "Gaming Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("43e9b598-7060-48bb-8895-e6055df457e0"),
                            Category = "Accessories",
                            Description = "Mechanical keyboard with RGB",
                            ImageUrl = "/images/keyboard.jpg",
                            Name = "Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("9fc1b483-6940-4678-ba8d-09d6bd53b190"),
                            Category = "Electronics",
                            Description = "27-inch 4K UHD monitor",
                            ImageUrl = "/images/monitor.jpg",
                            Name = "Monitor",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = new Guid("43f1887e-a0b2-4132-b587-7ccf5a3a6197"),
                            Category = "Wearables",
                            Description = "Fitness and health tracking",
                            ImageUrl = "/images/smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = new Guid("17b8340c-2cac-4116-970c-5da3e4c0c9ce"),
                            Category = "Audio",
                            Description = "Portable waterproof speaker",
                            ImageUrl = "/images/speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("00dc9ea1-de59-4367-8f19-d93aa43976fb"),
                            Category = "Accessories",
                            Description = "1080p HD webcam for streaming",
                            ImageUrl = "/images/webcam.jpg",
                            Name = "Webcam",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("83c1b0b7-b62d-4966-a710-258c7a7e9c17"),
                            Category = "Electronics",
                            Description = "10-inch Android tablet",
                            ImageUrl = "/images/tablet.jpg",
                            Name = "Tablet",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = new Guid("309baed5-2e2e-43f5-baa1-d6a2b7dae002"),
                            Category = "Storage",
                            Description = "1TB USB 3.0 drive",
                            ImageUrl = "/images/hdd.jpg",
                            Name = "External Hard Drive",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = new Guid("a82a9924-3e25-4e9c-86bb-e3e76c323863"),
                            Category = "Storage",
                            Description = "500GB NVMe SSD",
                            ImageUrl = "/images/ssd.jpg",
                            Name = "SSD",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("088c129f-3590-4c9e-a0c1-35066b92806f"),
                            Category = "Accessories",
                            Description = "Fast USB-C charger",
                            ImageUrl = "/images/charger.jpg",
                            Name = "Charger",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("9b271f98-55c8-4382-9423-ca15dd1a2056"),
                            Category = "Networking",
                            Description = "Wi-Fi 6 dual-band router",
                            ImageUrl = "/images/router.jpg",
                            Name = "Router",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = new Guid("cb3ceb2b-d0b9-439f-b22d-c703050c1812"),
                            Category = "Office",
                            Description = "All-in-one inkjet printer",
                            ImageUrl = "/images/printer.jpg",
                            Name = "Printer",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("1223d05d-1025-4a43-a016-cdcacbca26f3"),
                            Category = "Home Office",
                            Description = "LED lamp with adjustable brightness",
                            ImageUrl = "/images/lamp.jpg",
                            Name = "Desk Lamp",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("5ea21a07-e6c0-4013-a4af-c4f638e47b4e"),
                            Category = "Furniture",
                            Description = "Ergonomic mesh office chair",
                            ImageUrl = "/images/chair.jpg",
                            Name = "Office Chair",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("93d94e2b-708f-484b-80fa-a027140df751"),
                            Category = "Accessories",
                            Description = "Waterproof tech backpack",
                            ImageUrl = "/images/backpack.jpg",
                            Name = "Backpack",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("5272cdea-51a8-4355-b622-172d9d7874d7"),
                            Category = "Gadgets",
                            Description = "Mini drone with camera",
                            ImageUrl = "/images/drone.jpg",
                            Name = "Drone",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = new Guid("525d9950-d43b-49a6-a870-2b9cef86910e"),
                            Category = "Accessories",
                            Description = "Portable tripod for cameras",
                            ImageUrl = "/images/tripod.jpg",
                            Name = "Tripod",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = new Guid("58310f55-2555-4f96-b6fa-1e7b91ce5818"),
                            Category = "Photography",
                            Description = "DSLR camera with lens kit",
                            ImageUrl = "/images/camera.jpg",
                            Name = "Camera",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = new Guid("6491570f-e6db-4e75-874d-94a6c932b168"),
                            Category = "Appliances",
                            Description = "Programmable coffee maker",
                            ImageUrl = "/images/coffeemaker.jpg",
                            Name = "Coffee Maker",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("7984158e-5e4d-4b08-a99a-f52a67aa78da"),
                            Category = "Kitchen",
                            Description = "1.7L cordless kettle",
                            ImageUrl = "/images/kettle.jpg",
                            Name = "Electric Kettle",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("68d9cddd-872f-4427-bde2-6147e6ed0e08"),
                            Category = "Kitchen",
                            Description = "Compact 700W microwave",
                            ImageUrl = "/images/microwave.jpg",
                            Name = "Microwave Oven",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = new Guid("95fd2a84-cb0c-4fa9-b228-228492d2b022"),
                            Category = "Kitchen",
                            Description = "High-speed blender",
                            ImageUrl = "/images/blender.jpg",
                            Name = "Blender",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("a1682c07-e367-46e7-aaec-2682025048ac"),
                            Category = "Wearables",
                            Description = "Tracks steps and heart rate",
                            ImageUrl = "/images/tracker.jpg",
                            Name = "Fitness Tracker",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("99769a89-7114-499f-8326-e1abdbbcf65a"),
                            Category = "Entertainment",
                            Description = "Portable mini projector",
                            ImageUrl = "/images/projector.jpg",
                            Name = "Projector",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = new Guid("ec4cca39-c6bd-433b-b1fd-8445d9df1d9b"),
                            Category = "Entertainment",
                            Description = "Smart 55-inch 4K TV",
                            ImageUrl = "/images/tv.jpg",
                            Name = "TV",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = new Guid("2b7dcd55-3657-44fc-9cc5-ea3ea847e9b3"),
                            Category = "Accessories",
                            Description = "10000mAh portable charger",
                            ImageUrl = "/images/powerbank.jpg",
                            Name = "Power Bank",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("fd02223c-19ea-49f5-9a90-5a3e1ad2897f"),
                            Category = "Home",
                            Description = "Oscillating pedestal fan",
                            ImageUrl = "/images/fan.jpg",
                            Name = "Fan",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("fb75f465-080c-488e-a9ea-fba224531d90"),
                            Category = "Home",
                            Description = "Electric space heater",
                            ImageUrl = "/images/heater.jpg",
                            Name = "Heater",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("f072ff63-680e-459f-890c-ed89077bf791"),
                            Category = "Tools",
                            Description = "Household tool set",
                            ImageUrl = "/images/toolkit.jpg",
                            Name = "Tool Kit",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("83330713-fe2b-4c7a-a1ad-600d3044b4e5"),
                            Category = "Tools",
                            Description = "Magnetic precision screwdriver set",
                            ImageUrl = "/images/screwdrivers.jpg",
                            Name = "Screwdriver Set",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = new Guid("fd241b22-d84b-4aec-b784-9bac9052d593"),
                            Category = "Tools",
                            Description = "Rechargeable LED flashlight",
                            ImageUrl = "/images/flashlight.jpg",
                            Name = "Flashlight",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("d1d3336c-8ae5-4637-ac6b-f0aad2133780"),
                            Category = "Home",
                            Description = "HEPA filter air purifier",
                            ImageUrl = "/images/purifier.jpg",
                            Name = "Air Purifier",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("14fe2f8a-496a-4c05-8cb4-16192b1f7fe8"),
                            Category = "Home",
                            Description = "Cordless stick vacuum",
                            ImageUrl = "/images/vacuum.jpg",
                            Name = "Vacuum Cleaner",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = new Guid("83f4d044-f848-4f4d-9f8d-1cb93afd3b4e"),
                            Category = "Kitchen",
                            Description = "2-slice toaster with browning control",
                            ImageUrl = "/images/toaster.jpg",
                            Name = "Toaster",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = new Guid("0c69b913-1eb5-42b9-b7ce-256d858f7bfa"),
                            Category = "Kitchen",
                            Description = "Multi-function rice cooker",
                            ImageUrl = "/images/ricecooker.jpg",
                            Name = "Rice Cooker",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = new Guid("2fecc3d8-037e-4b51-a121-fad081ca2296"),
                            Category = "Appliances",
                            Description = "Steam iron with anti-drip",
                            ImageUrl = "/images/iron.jpg",
                            Name = "Iron",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("9a352eec-d8f0-4ce6-ad19-0ca378d5ed06"),
                            Category = "Appliances",
                            Description = "Professional hair dryer",
                            ImageUrl = "/images/hairdryer.jpg",
                            Name = "Hair Dryer",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("4fcec8bf-4574-4384-a468-43d94ddf0761"),
                            Category = "Smart Home",
                            Description = "Color-changing smart bulb",
                            ImageUrl = "/images/smartlight.jpg",
                            Name = "Smart Light",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("c61ae7ba-a860-49f3-8716-7f59e305376b"),
                            Category = "Smart Home",
                            Description = "Wi-Fi home security camera",
                            ImageUrl = "/images/securitycam.jpg",
                            Name = "Security Camera",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("457698b2-ac8c-44bc-adc2-7aec139b0490"),
                            Category = "Entertainment",
                            Description = "4K streaming media player",
                            ImageUrl = "/images/streamingstick.jpg",
                            Name = "Streaming Stick",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("7620436d-23a3-446e-9fbd-30075f8b3f30"),
                            Category = "Personal Care",
                            Description = "Rechargeable electric shaver",
                            ImageUrl = "/images/shaver.jpg",
                            Name = "Electric Shaver",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("5da81ded-36d4-49b0-8278-e2e3856a3bc5"),
                            Category = "Personal Care",
                            Description = "Electric toothbrush with timer",
                            ImageUrl = "/images/toothbrush.jpg",
                            Name = "Toothbrush",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("Productc.Api.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
